"""Pull Roblox Luau training data from GitHub repos + The Stack v2.

Usage:
    python scripts/pull_training_data.py [--github-only] [--stack-only] [--max-files N]

Collects real-world Luau code from:
1. Reputed Roblox open-source GitHub repos (Knit, ProfileService, Roact, etc.)
2. The Stack v2 on HuggingFace (Lua subset filtered for Roblox patterns)

Saves filtered files to data/raw_luau/ for downstream formatting.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw_luau"
RAW_DIR.mkdir(parents=True, exist_ok=True)

# === Reputed Roblox open-source repos ===
GITHUB_REPOS = [
    # Frameworks
    ("sleitnick/Knit", "Knit framework"),
    ("sleitnick/AeroGameFramework", "AeroGameFramework"),
    # Data persistence
    ("MadStudioRoblox/ProfileService", "ProfileService"),
    ("MadStudioRoblox/ReplicaService", "ReplicaService"),
    # UI
    ("Roblox/roact", "Roact UI library"),
    ("Roblox/rodux", "Rodux state management"),
    # Networking
    ("ffrostfall/ByteNet", "ByteNet networking"),
    # Utilities
    ("Quenty/NevermoreEngine", "Nevermore engine"),
    ("howmanysmall/Janitor", "Janitor cleanup utility"),
    # Physics / animation
    ("EgoMoose/Articles", "EgoMoose CFrame articles"),
    # Community projects
    ("Kampfkarren/Roblox", "Kampfkarren utilities"),
    ("evaera/Cmdr", "Cmdr command framework"),
    ("evaera/roblox-lua-promise", "Promise library"),
    ("LPGhatgern/luau-lsp", "Luau LSP examples"),
    # Game templates
    ("Roblox/Core-Scripts", "Roblox CoreScripts"),
]


def is_roblox_luau(content: str) -> bool:
    """Check if a Lua/Luau file is Roblox-specific."""
    roblox_patterns = [
        r"game:GetService",
        r"script\.Parent",
        r"Instance\.new",
        r"workspace\b",
        r"Players\b.*\bPlayerAdded",
        r"RemoteEvent|RemoteFunction",
        r"UserInputService|RunService",
        r"DataStore",
        r"ReplicatedStorage|ServerStorage|ServerScriptService",
        r"Humanoid|Character",
        r"BasePart|Part|MeshPart",
        r"BindableEvent|BindableFunction",
        r"TweenService|SoundService",
    ]
    matches = sum(1 for p in roblox_patterns if re.search(p, content))
    return matches >= 2  # At least 2 Roblox-specific patterns


def quality_filter(content: str) -> bool:
    """Filter for quality training data."""
    lines = content.strip().split("\n")
    n_lines = len(lines)

    # Length filter: 15-600 lines
    if n_lines < 15 or n_lines > 600:
        return False

    # Must have at least some structure (functions or methods)
    if not re.search(r"\bfunction\b", content):
        return False

    # Skip files that are mostly comments
    comment_lines = sum(1 for l in lines if l.strip().startswith("--"))
    if comment_lines / max(n_lines, 1) > 0.6:
        return False

    # Skip minified code (avg line length > 200)
    avg_len = sum(len(l) for l in lines) / max(n_lines, 1)
    if avg_len > 200:
        return False

    # Skip auto-generated / machine-generated
    first_lines = "\n".join(lines[:5]).lower()
    if any(w in first_lines for w in ["auto-generated", "autogenerated", "do not edit", "machine generated"]):
        return False

    return True


def pull_github_repos(max_files: int = 500) -> int:
    """Clone repos and extract Roblox Luau files."""
    print(f"\n{'='*50}")
    print("PULLING FROM GITHUB REPOS")
    print(f"{'='*50}")

    saved = 0
    github_dir = RAW_DIR / "github"
    github_dir.mkdir(exist_ok=True)

    for repo_url, description in GITHUB_REPOS:
        if saved >= max_files:
            break

        repo_name = repo_url.split("/")[-1]
        print(f"\n  [{saved}/{max_files}] {repo_url} ({description})...")

        with tempfile.TemporaryDirectory() as tmp:
            try:
                result = subprocess.run(
                    ["git", "clone", "--depth", "1", f"https://github.com/{repo_url}.git", tmp],
                    capture_output=True, text=True, timeout=60
                )
                if result.returncode != 0:
                    print(f"    SKIP: clone failed - {result.stderr[:100]}")
                    continue
            except (subprocess.TimeoutExpired, FileNotFoundError) as e:
                print(f"    SKIP: {e}")
                continue

            # Find all .lua and .luau files
            tmp_path = Path(tmp)
            lua_files = list(tmp_path.rglob("*.lua")) + list(tmp_path.rglob("*.luau"))
            print(f"    Found {len(lua_files)} Lua/Luau files")

            repo_saved = 0
            for f in lua_files:
                if saved >= max_files:
                    break
                try:
                    content = f.read_text(encoding="utf-8", errors="ignore")
                except Exception:
                    continue

                if not quality_filter(content):
                    continue

                # For Roblox-specific repos, we're more lenient (1 pattern enough)
                is_roblox_repo = any(kw in description.lower() for kw in
                    ["framework", "service", "roblox", "ui", "janitor", "cframe", "cmdr"])
                if is_roblox_repo or is_roblox_luau(content):
                    # Save with repo prefix for provenance
                    rel = f.relative_to(tmp_path)
                    safe_name = str(rel).replace("/", "_").replace("\\", "_")
                    out_path = github_dir / f"{repo_name}__{safe_name}"
                    out_path.write_text(content, encoding="utf-8")
                    saved += 1
                    repo_saved += 1

            print(f"    Saved {repo_saved} files")

    print(f"\n  Total GitHub files: {saved}")
    return saved


def pull_stack_v2(max_files: int = 300) -> int:
    """Pull Lua files from The Stack v2 on HuggingFace, filtered for Roblox patterns."""
    print(f"\n{'='*50}")
    print("PULLING FROM THE STACK V2")
    print(f"{'='*50}")

    try:
        from datasets import load_dataset
    except ImportError:
        print("  Installing 'datasets' library...")
        subprocess.run([sys.executable, "-m", "pip", "install", "datasets"], capture_output=True)
        from datasets import load_dataset

    stack_dir = RAW_DIR / "stack_v2"
    stack_dir.mkdir(exist_ok=True)

    saved = 0
    scanned = 0

    try:
        # The Stack v2 - stream Lua subset
        print("  Loading The Stack v2 (Lua subset, streaming)...")
        ds = load_dataset(
            "bigcode/the-stack-v2-dedup",
            "Lua",
            split="train",
            streaming=True,
            trust_remote_code=True,
        )

        for sample in ds:
            scanned += 1
            if saved >= max_files:
                break

            # Progress
            if scanned % 1000 == 0:
                print(f"    Scanned {scanned} files, saved {saved}...")

            content = sample.get("content", "")
            if not content:
                continue

            # Must be Roblox-specific
            if not is_roblox_luau(content):
                continue

            if not quality_filter(content):
                continue

            # Save
            file_id = sample.get("hexsha", f"stack_{saved}")[:12]
            out_path = stack_dir / f"stack__{file_id}.lua"
            out_path.write_text(content, encoding="utf-8")
            saved += 1

            if saved % 50 == 0:
                print(f"    Saved {saved}/{max_files} Roblox files (scanned {scanned})")

        print(f"\n  Total Stack v2 files: {saved} (scanned {scanned})")

    except Exception as e:
        print(f"  Stack v2 error: {e}")
        print("  Continuing with GitHub data only...")

    return saved


def pull_github_search(max_files: int = 200) -> int:
    """Use GitHub search API to find popular Roblox Luau repos."""
    print(f"\n{'='*50}")
    print("SEARCHING GITHUB FOR MORE ROBLOX REPOS")
    print(f"{'='*50}")

    try:
        import requests
    except ImportError:
        subprocess.run([sys.executable, "-m", "pip", "install", "requests"], capture_output=True)
        import requests

    github_search_dir = RAW_DIR / "github_search"
    github_search_dir.mkdir(exist_ok=True)

    # Search queries targeting Roblox Luau code
    queries = [
        "GetService Roblox language:lua stars:>5",
        "RemoteEvent Roblox language:lua stars:>3",
        "DataStoreService language:lua stars:>3",
        "PlayerAdded Humanoid language:lua",
        "TweenService Roblox language:lua stars:>2",
    ]

    saved = 0

    for query in queries:
        if saved >= max_files:
            break

        print(f"\n  Query: {query}")
        try:
            resp = requests.get(
                "https://api.github.com/search/repositories",
                params={"q": query, "sort": "stars", "per_page": 10},
                headers={"Accept": "application/vnd.github.v3+json"},
                timeout=15,
            )
            if resp.status_code != 200:
                print(f"    API error: {resp.status_code}")
                continue

            repos = resp.json().get("items", [])
            print(f"    Found {len(repos)} repos")

            for repo in repos:
                if saved >= max_files:
                    break

                full_name = repo["full_name"]
                # Skip repos we already cloned
                if any(full_name.endswith(r.split("/")[-1]) for r, _ in GITHUB_REPOS):
                    continue

                with tempfile.TemporaryDirectory() as tmp:
                    try:
                        result = subprocess.run(
                            ["git", "clone", "--depth", "1", repo["clone_url"], tmp],
                            capture_output=True, text=True, timeout=60
                        )
                        if result.returncode != 0:
                            continue
                    except Exception:
                        continue

                    tmp_path = Path(tmp)
                    lua_files = list(tmp_path.rglob("*.lua")) + list(tmp_path.rglob("*.luau"))

                    repo_saved = 0
                    for f in lua_files:
                        if saved >= max_files:
                            break
                        try:
                            content = f.read_text(encoding="utf-8", errors="ignore")
                        except Exception:
                            continue

                        if not quality_filter(content) or not is_roblox_luau(content):
                            continue

                        safe_name = f.name
                        repo_short = full_name.replace("/", "_")
                        out_path = github_search_dir / f"{repo_short}__{safe_name}"
                        out_path.write_text(content, encoding="utf-8")
                        saved += 1
                        repo_saved += 1

                    if repo_saved > 0:
                        print(f"    {full_name}: {repo_saved} files")

        except Exception as e:
            print(f"    Error: {e}")
            continue

    print(f"\n  Total GitHub search files: {saved}")
    return saved


def main():
    parser = argparse.ArgumentParser(description="Pull Roblox Luau training data")
    parser.add_argument("--github-only", action="store_true", help="Only pull from GitHub repos")
    parser.add_argument("--stack-only", action="store_true", help="Only pull from The Stack v2")
    parser.add_argument("--max-files", type=int, default=800, help="Max total files to collect")
    args = parser.parse_args()

    print("ROBLOX LUAU TRAINING DATA COLLECTION")
    print(f"Output: {RAW_DIR}")
    print(f"Max files: {args.max_files}\n")

    total = 0

    if not args.stack_only:
        # Phase 1: Known good repos
        n = pull_github_repos(max_files=min(args.max_files, 500))
        total += n

        # Phase 2: Search for more repos
        remaining = args.max_files - total
        if remaining > 0:
            n = pull_github_search(max_files=min(remaining, 200))
            total += n

    if not args.github_only:
        # Phase 3: The Stack v2
        remaining = args.max_files - total
        if remaining > 0:
            n = pull_stack_v2(max_files=min(remaining, 300))
            total += n

    # Summary
    print(f"\n{'='*50}")
    print(f"COLLECTION COMPLETE")
    print(f"{'='*50}")
    print(f"  Total files: {total}")
    print(f"  Location: {RAW_DIR}")

    # Count by source
    for subdir in ["github", "github_search", "stack_v2"]:
        p = RAW_DIR / subdir
        if p.exists():
            n = len(list(p.glob("*")))
            print(f"  {subdir}: {n} files")


if __name__ == "__main__":
    main()
